### ISSUE TITLE
Undefined index: ...

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExternalQueryLookup#21] opened 2015-11-30 15:15 UTC
The following notices popped up this night during the weekly full data refresh with "rebuildData.php" at 'sandbox.sm.o':

``` text
PHP Notice:  Undefined index: namespace in /.../w/extensions/SemanticExternalQueryLookup/src/DataValueDeserializer.php on line 83
PHP Notice:  Undefined index: fulltext in /.../w/extensions/SemanticExternalQueryLookup/src/DataValueDeserializer.php on line 89
```

**Comment by mwjames** [comment] 2015-12-01 10:38
Expected to be fixed with f8b3c56.

Nice catch :+1:

**Comment by kghbln** [comment] 2015-12-01 13:48
I guess this is what the sandbox is there for, too. Thanks for the fix.

**Comment by mwjames** [comment] 2015-12-04 14:06
> PHP Notice:  Undefined index: namespace in

The whole time I was wondering where this message came from. It was caused by `mainlabel=-`

```
{{#ask: [[Category:NumberApiTest]]
 |?Has number
 |mainlabel=-
 |source=mw-2501
 |format=sum
}}
```

vs 

```
{{#ask: [[Category:NumberApiTest]]
 |?Has number
 |source=mw-2501
 |format=sum
}}
```

f8b3c56 fixed the symptom but not the cause.

**Comment by mwjames** [comment] 2015-12-04 14:58
acbd932  should be a better fix and allows [0] to display the correct sum for when `|mainlabel=-` is used.

Should work in both cases now:

```
{{#ask:
 [[Category:City]]
 [[Population::+]]
 |?Population
 |mainlabel=-
 |limit=5
 |format=sum
 |source=smworg
}}
```

```
{{#ask:
 [[Category:City]]
 [[Population::+]]
 |?Population
 |limit=5
 |format=sum
 |source=smworg
}}
```

[0] http://sandbox.semantic-mediawiki.org/wiki/EmbeddedQueryResultFromAnExternalRepository#Math%20%28sum%29

**Closed as completed by mwjames** 2015-12-04 14:58 UTC
Labels: bug

**Comment by kghbln** [comment] 2015-12-04 21:19
Let's also see what "rebuildData.php" tells on Monday. Should be ok though. :)

**Comment by kghbln** [comment] 2015-12-07 09:47
No complaints from the script! :+1:
